### ISSUE TITLE
Potential Asteroid Modifications

### ISSUE THREAD

**Issue by Ldeerinck** [cdeerinck/SpaceShooter#2]
create some larger versions of asteroids and if the larger ones come in contact with another object then have them fragment into smaller asteroids radiating from point of contact(add shockwaves as desired)

**Comment by cdeerinck** [comment]
This issue has been resolved in the branch Asteroids.

**Comment by Ldeerinck** [comment]
Branch looks good go ahead with the merge

**Comment by cdeerinck** [comment]
Merged
